title: Book

tabs:
  item:
    label: Preview
    icon: page
    columns:
      main:
        width: 2/3
        sections:
          content:
            label: false
            type: fields
            fields:
              cover:
                label: Cover
                type: files
                width: 1/1
                multiple: false
                image:
                  icon: true
                  ratio: 4/3
                  back: white
                  cover: true
              itemheader:
                type: text
              itemtitle: 
                type: text
              iteminfo:
                type: text
      sidebar:
        width: 1/3
        sections:
          features:
            label: false
            type: fields
            fields:
              category:
                type: tags
  page:


