title: 
  en: Book
  it: Libro
create:
  title:
    label:
      en: Book title
      it: Titolo del Libro
  fields:
    - price
    - stock
  redirect: false
  status: unlisted

image:
  icon: false

columns:
  main:
    width: 2/3
    sections:
      content:
        label: false
        type: fields
        fields:
          gallery:
            label:
              en: Gallery
              it: Galleria immagini
            type: files
            template: image
            uploads: image
            multiple: true
            translate: false
            image:
              icon: true
              ratio: 4/3
              back: white
              cover: true
          galleryInfo:
            type: info
            label: false
            text:
              en: >
                The first two images appear on the page {{ page.parent.title }}.
              it: >
                Le prime due immagini compaiono nella griglia della pagina {{ page.parent.title }}.
          header:
            label:
              en: Author(s)
              it: Autore/i
            type: text
          itemTitle: 
            label:
              en: Title
              it: Titolo
            type: text
            placeholder: "{{ page.title }}"
          itemInfo:
            label:
              en: Information
              it: Informazioni
            type: writer
            marks:
              - bold
              - italic
              - link
              - email
              - clear
            nodes: false
          description:
            label:
              en: Text
              it: Testo
            type: writer
            marks:
              - bold
              - italic
              - link
              - email
              - clear
            nodes: false
  sidebar:
    width: 1/3
    sections:
      features:
        label: false
        type: fields
        fields:
          category:
            label:
              en: Category
              it: Categoria
            type: tags
            options:
              type: query
              query: page.siblings.pluck('category', ',', true)
          extends: fields/product-standards


