title: 
  en: Book
  it: Libro
create:
  status: unlisted

image:
  icon: false

columns:
  main:
    width: 2/3
    sections:
      content:
        label: false
        type: fields
        fields:
          gallery:
            label:
              en: Gallery
              it: Galleria immagini
            type: files
            multiple: true
            translate: false
            image:
              icon: true
              ratio: 4/3
              back: white
              cover: true
          galleryInfo:
            type: info
            label: false
            text:
              en: >
                The first two images appear on the page {{ page.parent.title }}.
              it: >
                Le prime due immagini compaiono nella griglia della pagina {{ page.parent.title }}.
          header:
            label:
              en: Author(s)
              it: Autore/i
            type: text
          panelTitle: 
            label:
              en: Title
              it: Titolo
            type: text
            placeholder: "{{ page.title }}"
            disabled: true
          itemInfo:
            label:
              en: Information
              it: Informazioni
            type: writer
            marks:
              - bold
              - italic
              - link
              - email
              - clear
            nodes: false
          description:
            label:
              en: Text
              it: Testo
            type: writer
            marks:
              - bold
              - italic
              - link
              - email
              - clear
            nodes: false
  sidebar:
    width: 1/3
    sections:
      features:
        label: false
        type: fields
        fields:
          category:
            label:
              en: Category
              it: Categoria
            type: tags
            # max: 1
            options:
              type: query
              query: page.siblings.pluck('category', ',', true)
          price:
            label:
              en: Price
              it: Prezzo
            type: number
            step: .01
            min: 0
            # before: "{{ kirby.option('ww.merx.currencySymbol') }}"
            required: true
            translate: false
          tax:
            label:
              en: Tax rate
              it: IVA %
            type: select
            options:
              - value: '4'
                text: 4%
              - value: '22'
                text: 22%
            # options: query
            # query:
            #   fetch: kirby.option('taxRates')
            #   text: "{{ arrayItem.value }} % ({{ arrayItem.key }})"
            #   value: "{{ arrayItem.key }}"
            translate: false
          stock:
            label:
              en: Stock
              it: Quantità disponibile
            type: number
            placeholder:
              en: 0
              it: 0
            translate: false


