title: 
  en: Project
  it: Progetto
create:
  status: unlisted


columns:
  main:
    width: 2/3
    sections:
      content:
        label: false
        type: fields
        fields:
          gallery:
            label:
              en: Gallery
              it: Galleria immagini
            type: files
            multiple: true
            translate: false
            image:
              icon: true
              ratio: 4/3
              back: white
              cover: true
          cover:
            label: 
              en: Thumbnail
              it: Anteprima
            type: files
            multiple: false
            translate: false
            image:
              icon: true
              ratio: 4/3
              back: white
              cover: true
          header:
            label:
              en: Header
              it: Intestazione
            type: text
          panelTitle: 
            label:
              en: Title
              it: Titolo
            type: text
            placeholder: "{{ page.title }}"
            disabled: true
          info:
            label:
              en: Information
              it: Informazioni
            type: writer
            marks:
              - bold
              - italic
              - link
              - email
              - clear
            nodes: false
          description:
            label:
              en: Text
              it: Testo
            type: writer
            marks:
              - bold
              - italic
              - link
              - email
              - clear
            nodes: false
  sidebar:
    width: 1/3
    sections:
      features:
        label: false
        type: fields
        fields:
          category:
            label:
              en: Category
              it: Categoria
            type: tags
            max: 1
            options:
              type: query
              query: page.siblings.pluck("category", ",", true)


