title: Site

tabs:
  pages:
    label:
      en: Website pages
      it: Pagine del sito web
    icon: page
    sections:
      home:
        label:
          en: Home
          it: Home
        type: pages
        max: 1
        sortable: false
        template:
          - home
      mainPages:
        label: 
          en: Main pages
          it: Pagine principali
        type: pages
        max: 3
        sortable: false
        template:
          - shop
          - projects
          - agenda
      pages:
        label:
          en: Other pages
          it: Altre pagine
        type: pages
        template:
          - page
  about:
    label:
      en: Contacts and biography
      it: Contatti e biografia
    icon: info
    columns:
      main:
        width: 1/3
        sections:
          aboutInfo:
            type: fields
            fields:
              contact:
                label:
                  en: Contact
                  it: Contatti
                type: blocks
                fieldsets:
                  - contactblock
          buttons:
            type: fields
            fields:
              newsletter:
                type: url
              facebook:
                type: url
              instagram:
                type: url
      sidebar:
        width: 2/3
        sections:
          aboutText:
            type: fields
            fields:
              about:
                label:
                  en: Biography
                  it: Biografia
                type: writer
                marks:
                  - bold
                  - italic
                  - link
                  - email
                  - clear
                nodes: false
  orders:
    icon: draft
    label:
      en: Orders
      it: Ordini
    sections:
      orders:
        extends: sections/orders
  shopSettings:
    label:
      en: Shop Settings
      it: Gestione shop
    icon: settings
    columns:
      main:
        width: 2/3    
        sections:
          checkoutPage:
            headline:
              en: Checkout Page
              it: Checkout
            type: pages
            template: checkout
            max: 1
          shippingPage:
            headline:
              en: Shipping Page
              it: Spedizioni
            type: pages
            template: shipping
            max: 1
      sidebar:
        width: 1/3
        sections:
          paymentSetting:
            type: fields
            fields:
              recipient:
                label:
                  en: Recipient
                  it: Destinatario
                type: text
                translate: false
                width: 1/2
              iban:
                label:
                  en: IBAN
                  it: IBAN
                type: text
                translate: false
                minlength: 1
                maxlength: 27
                width: 1/2
          shopSettings:
            type: fields
            fields:
              maxAmount:
                label:
                  en: Max Amount per Product
                  it: Numero massimo acquistabile per prodotto
                type: number
                translate: false
                # required: true
                width: 1/2


