title: Site

tabs:
  pages:
    label: Website pages
    icon: angle-right
    sections:
      home:
        type: pages
        template:
          - home
      pages:
        type: pages
        template:
          - publishing
          - projects
  about:
    label: About
    icon: angle-right
    columns:
      main:
        width: 1/3
        sections:
          aboutInfo:
            type: fields
            fields:
              contact:
                label: Contatti
                type: blocks
                fieldsets:
                  - contactblock
          buttons:
            type: fields
            fields:
              subscribeText:
                type: text
              subscribeLink:
                type: url
              fbText:
                type: text
              fbLink:
                type: url
              igText:
                type: text
              igLink:
                type: url
      sidebar:
        width: 2/3
        sections:
          aboutText:
            type: fields
            fields:
              about:
                label: About
                type: blocks
                fieldsets:
                  - text

